/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { ApiError } from './apiError';

/**
 * Creates an instance of ErrorError
 */
interface ErrorError {
  code: number;
  message: string;
}

export class ErrorErrorError extends ApiError<ErrorError> {}
