/**
 * WebRtcLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const DeviceApiVersionEnum = {

    /**
     * TODO: Write general description for this element
     */
    V_3: 'v3',

    /**
     * TODO: Write general description for this element
     */
    V_2: 'v2',

};

module.exports = DeviceApiVersionEnum;
