/**
 * WebRtcLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of Participant
 */
class Participant extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.id = this.constructor.getValue(obj.id);
        this.callbackUrl = this.constructor.getValue(obj.callbackUrl);
        this.permissions = this.constructor.getValue(obj.permissions);
        this.sessions = this.constructor.getValue(obj.sessions);
        this.subscriptions = this.constructor.getValue(obj.subscriptions);
        this.tag = this.constructor.getValue(obj.tag);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'id', realName: 'id' },
            { name: 'callbackUrl', realName: 'callbackUrl' },
            { name: 'permissions', realName: 'permissions', type: 'Permissions' },
            { name: 'sessions', realName: 'sessions', array: true },
            { name: 'subscriptions', realName: 'subscriptions', type: 'Subscriptions' },
            { name: 'tag', realName: 'tag' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = Participant;
