/**
 * WebRtcLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const PublishPermissionEnum = {

    /**
     * TODO: Write general description for this element
     */
    AUDIO: 'AUDIO',

    /**
     * TODO: Write general description for this element
     */
    VIDEO: 'VIDEO',

};

module.exports = PublishPermissionEnum;
