/**
 * WebRtcLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const Environments = {

    /**
     * Production WebRTC APIs
     */
    PRODUCTION: 'production',

    /**
     * Staging WebRTC APIs
     */
    ENVIRONMENT_2: 'environment2',

};

module.exports = Environments;
