/**
 * WebRtcLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const Session = require('../lib/Models/Session');
const Participant = require('../lib/Models/Participant');
const Subscriptions = require('../lib/Models/Subscriptions');
const ParticipantSubscription = require('../lib/Models/ParticipantSubscription');
const AccountsParticipantsResponse = require('../lib/Models/AccountsParticipantsResponse');
const ErrorException = require('../lib/Exceptions/ErrorException');

const classMap = {
    Session,
    Participant,
    Subscriptions,
    ParticipantSubscription,
    AccountsParticipantsResponse,
    ErrorException,
};

/**
 * Factory class to create instances of models and exception classes
 */
class ModelFactory {
    /**
     * Creates instance of a model class
     * @param  modelName  {string}  Name of class to instantiate
     * @returns  {object} Instance of the model class
     */
    static getInstance(modelName) {
        return new classMap[modelName]();
    }
}

module.exports = ModelFactory;
