/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema';
import { Participant, participantSchema } from './participant';

export interface AccountsParticipantsResponse {
  /** A participant object */
  participant?: Participant;
  /**
   * Auth token for the returned participant
   * This should be passed to the participant so that they can connect to the platform
   */
  token?: string;
}

export const accountsParticipantsResponseSchema: Schema<AccountsParticipantsResponse> = object(
  {
    participant: ['participant', optional(lazy(() => participantSchema))],
    token: ['token', optional(string())],
  }
);
