/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { object, Schema, string, optional, array, lazy } from '../schema';

export interface ParticipantSubscription {
  /** Participant the subscriber should be subscribed to */
  participantId: string;
  /** Stream aliases of the participant the subscriber should be subscribed to. (if empty all aliases are assumed) */
  streamAliases?: string[];
}

export const participantSubscriptionSchema: Schema<ParticipantSubscription> = object(
  {
    participantId: ['participantId', string()],
    streamAliases: ['streamAliases', optional(array(lazy(() => string())))]
  }
);
