/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for PublishPermissionEnum
 */
export enum PublishPermissionEnum {
  AUDIO = 'AUDIO',
  VIDEO = 'VIDEO',
}

/**
 * Schema for PublishPermissionEnum
 */
export const publishPermissionEnumSchema: Schema<PublishPermissionEnum> = stringEnum(PublishPermissionEnum);
