/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

/** A session object */
export interface Session {
  /** Unique id of the session */
  id?: string;
  /** User defined tag to associate with the session */
  tag?: string;
}

export const sessionSchema: Schema<Session> = object({
  id: ['id', optional(string())],
  tag: ['tag', optional(string())],
});
