/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import {
  ParticipantSubscription,
  participantSubscriptionSchema,
} from './participantSubscription';

export interface Subscriptions {
  /**
   * Session the subscriptions are associated with
   * If this is the only field, the subscriber will be subscribed to all participants in the session (including any participants that are later added to the session)
   */
  sessionId?: string;
  /** Subset of participants to subscribe to in the session. Optional. */
  participants?: ParticipantSubscription[];
}

export const subscriptionsSchema: Schema<Subscriptions> = object({
  sessionId: ['sessionId', optional(string())],
  participants: [
    'participants',
    optional(array(lazy(() => participantSubscriptionSchema))),
  ],
});
